# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterUser',
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
